# Generated by Django 3.2.7 on 2021-10-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('metal', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('grossWt', models.CharField(max_length=20)),
                ('netWt', models.CharField(max_length=20)),
                ('bisNo', models.CharField(max_length=20)),
                ('purity', models.CharField(max_length=20)),
                ('purchaseRate', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
