# Generated by Django 3.2.7 on 2021-10-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='linkedAccounts',
            field=models.CharField(default='Daya Gada, Tapu Gada', max_length=200),
            preserve_default=False,
        ),
    ]
