# Generated by Django 3.2.7 on 2021-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageRecord',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=20)),
                ('items', models.CharField(max_length=50)),
                ('grossWt', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('roi', models.CharField(max_length=20)),
                ('principal', models.CharField(max_length=20)),
                ('interest', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=20)),
                ('months', models.CharField(max_length=20)),
                ('isActive', models.BooleanField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
