# Generated by Django 3.2.7 on 2021-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='comments',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='gst',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='inventoryId',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
