# Generated by Django 3.2.7 on 2021-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_record', '0002_auto_20211113_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='isActive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='subTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='totalAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
